 # KWEB数据分析

In [1]:
#imports

import yfinance as yf
import pandas as pd
import datetime as dt
import getdata as gd
import warnings


warnings.filterwarnings('ignore')

In [2]:
print('This notebook was refreshed at %s'%(dt.datetime.now()))

This notebook was refreshed at 2022-01-08 11:45:09.961825

本笔记分析KWEB的数据以回答以下问题：
1. 当前的估值是否合理？
2. 中短期趋势如何？

In [3]:
#init

pd.options.display.float_format = '{:,.2f}'.format
df_port=pd.read_csv('../data/share/kweb_holdings.csv')

## 估值指标监测

In [4]:
#df_stock=gd.get_port_holding_info(df_port)
# df_stock.to_csv('../data/share/kweb_holidngs_info.csv')

In [5]:
df_stock=pd.read_csv('../data/share/kweb_holidngs_info.csv')
df_metric=gd.get_port_holding_metric(df_stock)

In [7]:
df_metric

,ticker,weight,market_cap,revenue,revenue_growth,cashflow,net_income,gross_profit,pcf,pe_ttm,pe_fwd,peg,roe
0,0700.HK,0.10,"545,403,250,783.68","86,118,393,990.51",0.14,"27,076,732,168.23","29,641,014,644.10","34,726,961,707.71",20.14,40.22,22.89,0.96,0.24
1,3690.HK,0.07,"160,448,686,648.53","26,090,693,621.62",0.38,"-150,571,773.71","-3,203,429,574.91","5,196,766,564.73","-1,065.60",NaN,-200.00,-0.87,-0.18
2,BABA,0.07,"351,903,219,712.00","127,690,659,377.91",0.29,"30,840,972,738.97","19,501,402,373.55","46,658,831,361.35",11.41,18.26,13.41,85.06,0.11
3,BIDU,0.06,"53,367,889,920.00","19,064,541,923.64",0.13,"3,358,717,707.01","2,129,303,186.09","8,315,861,931.88",15.89,25.30,17.15,67.70,0.05
4,BZ,0.05,"15,099,504,640.00","597,566,705.06",1.05,"244,259,232.26","-327,151,942.06","267,028,310.74",61.82,NaN,69.66,NaN,NaN
5,JD,0.05,"105,995,141,120.00","141,025,893,542.37",0.26,"6,431,084,461.69","4,063,126,172.44","9,465,538,971.33",16.48,26.57,32.65,70.05,0.12
6,BEKE,0.04,"24,854,083,584.00","13,418,788,224.64",-0.12,"535,956,544.68","187,817,408.51","2,641,824,028.25",46.37,133.78,33.66,144.23,0.03
7,TCOM,0.04,"16,040,647,680.00","3,181,810,995.16",-0.02,NaN,"201,820,771.57","2,238,361,585.36",NaN,80.97,41.02,NaN,0.01
8,PDD,0.04,"70,058,909,696.00","14,614,266,449.94",0.51,"4,282,393,003.41","-35,605,696.87","6,301,136,564.59",16.36,NaN,41.41,-11.39,-0.00
9,1024.HK,0.04,"37,731,694,174.50","11,712,798,696.63",0.33,"-421,984,338.61","-14,280,288,964.49","3,731,590,383.63",-89.41,NaN,-17.82,NaN,NaN
10,9988.HK,0.04,"358,090,064,092.50","127,690,659,377.91",0.29,"30,840,972,738.97","19,501,402,373.55","46,658,831,361.35",11.61,NaN,NaN,NaN,0.11
11,6618.HK,0.03,"23,404,875,309.04","3,798,697,699.33",0.55,"826,352,296.14","-1,932,144,800.26","770,506,891.63",28.32,NaN,NaN,NaN,-0.73
12,YMM,0.03,"9,012,554,752.00","638,994,026.13",0.69,NaN,"-900,592,896.82","43,362,320.96",NaN,NaN,33.20,NaN,-0.22
13,NTES,0.03,"66,903,515,136.00","13,004,622,357.53",0.19,"3,881,661,610.49","1,902,002,434.30","6,108,431,886.85",17.24,35.51,20.56,NaN,0.13
14,9618.HK,0.02,"107,441,499,852.85","141,025,893,542.37",0.26,"6,431,084,461.69","4,063,126,172.44","9,465,538,971.33",16.71,NaN,25.26,0.97,0.12
15,BILI,0.02,"14,719,252,480.00","2,733,203,082.12",0.61,NaN,"-866,358,478.07","445,036,111.59",NaN,NaN,-18.66,-503.83,-0.35
16,3888.HK,0.02,"5,845,563,645.80","964,415,875.29",0.08,"371,694,152.38","149,014,549.71","732,847,887.78",15.73,NaN,33.74,-2.41,0.05
17,TME,0.02,"11,424,847,872.00","5,009,793,212.06",0.03,"984,189,637.69","578,197,687.33","1,457,559,640.68",11.61,19.57,17.31,211.04,0.08
18,9999.HK,0.02,"66,791,614,424.06","13,004,622,357.53",0.19,"3,881,661,610.49","1,902,002,434.30","6,108,431,886.85",17.21,NaN,14.42,0.90,0.13
19,0241.HK,0.01,"10,860,155,872.57","2,775,686,108.84",0.31,"163,075,415.40","-26,107,271.77","564,542,526.52",66.60,NaN,NaN,NaN,-0.01
20,LU,0.01,"13,222,550,528.00","9,928,621,324.70",0.22,"507,521,126.16","2,630,051,518.03","7,731,798,729.97",26.05,5.12,4.44,0.28,0.22
21,VIPS,0.01,"6,043,826,176.00","18,599,938,373.16",0.07,NaN,"894,265,963.55","3,335,261,866.28",NaN,6.96,6.11,29.08,0.20
22,0772.HK,0.01,"6,321,670,590.21","1,505,451,504.19",0.33,"156,590,194.48","-16,492,423.66","663,450,687.29",40.37,NaN,22.98,10.23,-0.01
23,0909.HK,0.01,"4,391,120,810.01","314,680,411.18",0.17,"58,772,309.62","-95,452,761.02","211,737,410.68",74.71,NaN,NaN,NaN,-0.16
24,ZH,0.01,"2,790,679,808.00","385,451,178.78",1.15,NaN,"-210,911,160.20","118,741,595.68",NaN,NaN,-23.67,NaN,-0.20
25,9626.HK,0.01,"14,717,199,664.94","2,733,203,082.12",0.61,NaN,"-866,358,478.07","445,036,111.59",NaN,NaN,-18.13,0.78,-0.35
26,YY,0.01,"3,849,561,344.00","2,658,517,504.00",-0.33,NaN,"-316,405,600.00","3,731,434,000.00",NaN,NaN,33.14,2.53,-0.05
27,6060.HK,0.01,"5,370,033,246.35","3,061,248,912.19",0.14,"486,222,611.59","128,275,276.74","1,283,049,857.61",11.04,NaN,NaN,NaN,0.03
28,0780.HK,0.01,"3,962,737,663.67","1,175,828,814.58",0.01,"296,601,943.26","121,111,737.46","663,749,814.50",13.36,NaN,NaN,NaN,0.05
29,ATHM,0.01,"4,158,084,608.00","1,257,694,580.07",-0.24,NaN,"488,438,999.78","1,221,320,749.58",NaN,8.64,9.24,-41.87,0.15
30,WB,0.01,"7,842,410,496.00","2,154,205,952.00",0.30,"885,502,976.00","341,628,000.00","1,387,751,000.00",8.86,22.41,9.98,0.64,0.11
31,QFIN,0.01,"3,115,929,600.00","2,436,745,467.03",0.25,"937,847,376.63","887,505,724.84","1,622,872,162.86",3.32,3.61,3.55,NaN,0.51
32,1833.HK,0.01,"3,991,716,136.71","1,243,782,836.11",0.39,"-166,142,990.85","-252,973,396.89","292,140,894.42",-24.03,NaN,NaN,NaN,-0.13
33,2013.HK,0.01,"2,326,101,631.41","375,255,464.16",0.45,"-63,171,155.05","-183,434,874.21","158,043,683.85",-36.82,NaN,NaN,NaN,-0.51
34,TAL,0.01,"2,205,493,248.00","4,495,754,752.00",0.59,"954,732,032.00","-115,990,000.00","2,447,194,000.00",2.31,NaN,6.58,0.38,-0.04
35,KC,0.01,"3,262,531,328.00","1,304,282,415.65",0.40,"-160,628,806.12","-190,538,544.18","55,936,789.21",-20.31,NaN,-21.77,NaN,-0.12
36,IQ,0.01,"3,496,532,480.00","4,798,568,003.69",0.06,"-999,064,345.02","-933,192,933.34","411,833,774.19",-3.50,NaN,-4.71,-2.15,-0.94
37,JOBS,0.01,"3,060,974,592.00","664,120,687.12",0.19,NaN,"98,336,857.56","387,593,971.33",NaN,31.50,2.02,NaN,0.05
38,2158.HK,0.01,"2,569,304,101.70","166,063,235.29",0.81,NaN,"-462,000,508.79","51,291,307.52",NaN,NaN,NaN,NaN,NaN
39,MOMO,0.01,"1,894,334,592.00","2,302,870,694.29",-0.00,"302,853,062.12","310,324,512.21","1,104,280,371.38",6.25,6.36,5.44,-172.90,0.14
40,1060.HK,0.00,"2,683,466,567.86","515,581,241.06",0.47,"-28,001,065.12","1,964,775.35","221,182,873.50",-95.83,33.33,NaN,NaN,-0.00
41,API,0.00,"1,668,542,336.00","160,848,928.00",0.46,"-23,082,716.00","-57,363,456.00","86,364,070.00",-72.29,NaN,-25.71,0.15,-0.07
42,2400.HK,0.00,"2,154,053,237.13","436,512,465.77",-0.04,"-49,976,494.08","-81,879,689.86","240,058,286.52",-43.10,NaN,NaN,NaN,-0.19
43,VNET,0.00,"1,273,173,248.00","907,680,782.14",0.25,"157,909,395.32","-80,040,112.33","168,603,548.33",8.06,NaN,-21.32,-6.13,-0.06
44,DADA,0.00,"2,683,200,000.00","989,225,158.70",0.30,NaN,"-359,719,968.05","159,619,860.21",NaN,NaN,-22.49,2.07,-0.45
45,CD,0.00,"2,060,419,968.00","411,090,248.92",0.58,"154,513,391.04","27,363,950.79","114,821,759.95",13.33,74.74,47.33,NaN,0.02
46,DAO,0.00,"1,587,209,472.00","803,422,488.10",0.55,NaN,"-223,569,158.43","227,876,647.99",NaN,NaN,-31.50,NaN,NaN
47,9923.HK,0.00,"1,457,206,891.05","410,266,078.07",0.30,"-39,797,080.57","81,325,622.90","116,529,401.85",-36.62,NaN,NaN,NaN,0.17
48,BZUN,0.00,"1,015,187,008.00","1,499,565,257.23",0.04,NaN,"4,365,784.42","511,782,377.45",NaN,237.80,15.25,-359.27,0.01
49,HUYA,0.00,"1,661,324,032.00","1,807,149,379.31",0.06,NaN,"180,091,980.14","355,390,396.04",NaN,9.35,-233.33,153.98,0.11
50,DOYU,0.00,"807,780,864.00","1,426,943,715.44",-0.08,NaN,"-82,623,889.54","244,495,421.48",NaN,NaN,-49.80,-2.82,-0.09
51,OCFT,0.00,"893,086,208.00","615,462,155.39",0.21,"-26,364,248.53","-201,861,827.69","194,841,032.10",-33.87,NaN,-7.39,-3.69,-0.26
52,GOTU,0.00,"423,064,960.00","1,308,301,141.05",0.35,NaN,"-611,769,993.54","840,219,358.74",NaN,NaN,-9.17,-0.64,-1.52

In [8]:
df_port_metric=gd.get_port_metric(df_metric)

In [9]:
df_port_metric

                                0
market_cap     129,948,352,305.99
revenue         39,244,005,489.64
revenue_growth              18.89
ps                           3.31
gross_profit    11,467,114,583.62
pgp                         11.33
gross_margin                29.22
cashflow         7,240,434,338.10
pcf                         17.95
cf_rate                      5.57
cf_margin                   18.45
net_income       4,872,102,803.13
pe                          26.67
income_rate                  3.75
profit_margin               12.41